---
# tasks file for kibana
- name: Upload .tar.gz file containing binaries from local storage
  copy:
    src: "{{ playbook_dir }}/files/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    mode: '0755'
  register: download_kibana_binaries
  until: download_kibana_binaries is succeeded
- name: Create directrory for Kibana
  file:
    state: directory
    path: "{{ kibana_home }}"
    mode: '0755'
  tags: kibana
- name: Extract Kibana in the installation directory
  unarchive:
    copy: false
    src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "{{ kibana_home }}"
    mode: '0755'
    extra_opts: [--strip-components=1]
    creates: "{{ kibana_home }}/bin/kibana"
  tags:
    - kibana
- name: Set environment Kibana
  template:
    src: templates/kbn.sh.j2
    dest: /etc/profile.d/kbn.sh
    mode: '0755'
  tags: kibana